repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-yaml
      exclude: packer/.kitchen.yml$
      exclude: \.tf$
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: flake8
    - id: debug-statements
    - id: detect-private-key
      exclude: \_spec.rb$
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.26.0
    hooks:
    - id: terraform_fmt
  - repo: https://github.com/stratasan/hadolint-pre-commit
    rev: cdefcb096e520a6daa9552b1d4636f5f1e1729cd
    hooks:
    - id: hadolint
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.5.6
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
