version: "3.8"

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=appsync,sns,es,sqs,firehose,dynamodb,s3,cloudformation,sts,logs,iam,lambda,ssm,stepfunctions,glue
      - DEBUG=${DEBUG-:0}
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER="${TMPDIR:-/tmp}/localstack"
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - DNS_ADDRESS=0
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

