env_vars:
  LOG_THRESHOLD: DEBUG
  infra: dev
  db_secret: ue1-dev-di-didb-ro
  aws_account_id: 111077548247
  region: "us-east-1"
  cloudwatch_rule: "ue1-dev-pullWatcherEvent"
  ENV: dev
  glue_source_bucket: vh-master-ue1-dev-data-v1-0-0
  glue_destination_bucket: vh-master-ue1-dev-data-lake
  glue_job_name: dev_vh-dit-epic-data-preprocessing
aws_account_id: 111077548247
region: "us-east-1"
deploy_bucket: vh-serverless-master-ue1
